package oceania.entity.render.model;

import static org.lwjgl.opengl.GL11.*;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSubmarine extends ModelBase
{
	// fields
	ModelRenderer	Bottom;
	ModelRenderer	FrontGlass;
	ModelRenderer	ChairBase;
	ModelRenderer	ChairHeadRod1;
	ModelRenderer	ChairHandRight;
	ModelRenderer	ChairSeat;
	ModelRenderer	ChairHandLeft;
	ModelRenderer	ChairSeatBack;
	ModelRenderer	ChairHead;
	ModelRenderer	ChairHeadRod;
	ModelRenderer	ChairBaseRod;
	ModelRenderer	GlassBack;
	ModelRenderer	GlassRight;
	ModelRenderer	GlassTopRight;
	ModelRenderer	GlassTopLeft;
	ModelRenderer	GlassTopBack;
	ModelRenderer	GlassTopFront;
	ModelRenderer	TopLid;
	ModelRenderer	BottomLid;
	ModelRenderer	BottomBaseRight;
	ModelRenderer	BottomTopRight;
	ModelRenderer	BottomBack;
	ModelRenderer	BottomBaseLeftFront;
	ModelRenderer	BottomTopLeft;
	ModelRenderer	BottomBaseLeft;
	ModelRenderer	BottomBaseBackLeft;
	ModelRenderer	AdvancedMachinePart;
	ModelRenderer	TopLidIronBottom;
	ModelRenderer	AdvancedMachinePart1;
	ModelRenderer	AdvancedMachinePart2;
	ModelRenderer	TopLidIronTop;
	ModelRenderer	TopMachinePartRight;
	ModelRenderer	GlassLeft;
	ModelRenderer	MahcinePartConnection;
	ModelRenderer	TopMachinePartLeft;
	ModelRenderer	AdvancedMachinePartBack;
	ModelRenderer	AdvancedMahinePart3;
	ModelRenderer	AdvancedMachinePart4;
	ModelRenderer	AdvancedMachinePart5;
	ModelRenderer	AdvancedMachinePart6;
	ModelRenderer	AdvancedMachinePart7;
	ModelRenderer	BottomBaseRightFront;
	ModelRenderer	AdvancedMachinePart8;
	ModelRenderer	AdvancedMachinePart9;
	ModelRenderer	AdvancedMachinePart10;
	ModelRenderer	AdvancedMachinePart11;
	ModelRenderer	AdvancedMachinePart12;
	ModelRenderer	AdvancedMachinePart13;
	ModelRenderer	AdvancedMachinePart14;
	ModelRenderer	AdvancedMachinePart15;
	ModelRenderer	AdvancedMachinePart16;
	ModelRenderer	AdvancedMachinePart17;
	ModelRenderer	AdvancedMachinePart18;
	ModelRenderer	AdvancedMachinePart19;
	ModelRenderer	AdvancedMachinePart20;
	ModelRenderer	AdvancedMachinePart21;
	ModelRenderer	AdvancedMachinePart22;
	ModelRenderer	AdvancedMachinePart23;
	ModelRenderer	AdvancedMachinePart24;
	
	public ModelSubmarine()
	{
		textureWidth = 512;
		textureHeight = 256;
		
		Bottom = new ModelRenderer(this, 0, 113);
		Bottom.addBox(0F, 0F, 0F, 30, 1, 32);
		Bottom.setRotationPoint(-10F, 23F, -9F);
		Bottom.setTextureSize(512, 256);
		Bottom.mirror = true;
		setRotation(Bottom, 0F, 0F, 0F);
		FrontGlass = new ModelRenderer(this, 0, 220);
		FrontGlass.addBox(0F, 0F, 0F, 30, 32, 1);
		FrontGlass.setRotationPoint(-10F, -9F, 23F);
		FrontGlass.setTextureSize(512, 256);
		FrontGlass.mirror = true;
		setRotation(FrontGlass, 0F, 0F, 0F);
		ChairBase = new ModelRenderer(this, 104, 51);
		ChairBase.addBox(0F, 0F, 0F, 14, 1, 12);
		ChairBase.setRotationPoint(-2F, 22F, -3F);
		ChairBase.setTextureSize(512, 256);
		ChairBase.mirror = true;
		setRotation(ChairBase, 0F, 0F, 0F);
		ChairHeadRod1 = new ModelRenderer(this, 0, 0);
		ChairHeadRod1.addBox(0F, 0F, 0F, 1, 1, 3);
		ChairHeadRod1.setRotationPoint(7F, -1F, 1F);
		ChairHeadRod1.setTextureSize(512, 256);
		ChairHeadRod1.mirror = true;
		setRotation(ChairHeadRod1, 1.658063F, 0F, 0F);
		ChairHandRight = new ModelRenderer(this, 26, 0);
		ChairHandRight.addBox(0F, 0F, 0F, 4, 2, 6);
		ChairHandRight.setRotationPoint(11F, 12F, 2F);
		ChairHandRight.setTextureSize(512, 256);
		ChairHandRight.mirror = true;
		setRotation(ChairHandRight, 0F, 0F, -1.58825F);
		ChairSeat = new ModelRenderer(this, 45, 49);
		ChairSeat.addBox(0F, 0F, 0F, 15, 2, 8);
		ChairSeat.setRotationPoint(-2F, 12F, 0F);
		ChairSeat.setTextureSize(512, 256);
		ChairSeat.mirror = true;
		setRotation(ChairSeat, 0F, 0F, 0F);
		ChairHandLeft = new ModelRenderer(this, 26, 0);
		ChairHandLeft.addBox(0F, 0F, 0F, 4, 2, 6);
		ChairHandLeft.setRotationPoint(-2F, 12F, 2F);
		ChairHandLeft.setTextureSize(512, 256);
		ChairHandLeft.mirror = true;
		setRotation(ChairHandLeft, 0F, 0F, -1.570796F);
		ChairSeatBack = new ModelRenderer(this, 1, 49);
		ChairSeatBack.addBox(0F, 0F, 0F, 15, 2, 14);
		ChairSeatBack.setRotationPoint(-2F, 12F, 0F);
		ChairSeatBack.setTextureSize(512, 256);
		ChairSeatBack.mirror = true;
		setRotation(ChairSeatBack, 1.570796F, 0F, 0F);
		ChairHead = new ModelRenderer(this, 0, 9);
		ChairHead.addBox(0F, 0F, 0F, 7, 2, 5);
		ChairHead.setRotationPoint(2F, -3F, 0F);
		ChairHead.setTextureSize(512, 256);
		ChairHead.mirror = true;
		setRotation(ChairHead, 1.658063F, 0F, 0F);
		ChairHeadRod = new ModelRenderer(this, 0, 0);
		ChairHeadRod.addBox(0F, 0F, 0F, 1, 1, 3);
		ChairHeadRod.setRotationPoint(3F, -1F, 1F);
		ChairHeadRod.setTextureSize(512, 256);
		ChairHeadRod.mirror = true;
		setRotation(ChairHeadRod, 1.658063F, 0F, 0F);
		ChairBaseRod = new ModelRenderer(this, 17, 20);
		ChairBaseRod.addBox(0F, 0F, 0F, 6, 9, 4);
		ChairBaseRod.setRotationPoint(2F, 14F, 1F);
		ChairBaseRod.setTextureSize(512, 256);
		ChairBaseRod.mirror = true;
		setRotation(ChairBaseRod, 0F, 0F, 0F);
		GlassBack = new ModelRenderer(this, 0, 191);
		GlassBack.addBox(0F, 0F, 0F, 1, 32, 30);
		GlassBack.setRotationPoint(-10F, -9F, -6F);
		GlassBack.setTextureSize(512, 256);
		GlassBack.mirror = true;
		setRotation(GlassBack, 0F, 1.570796F, 0F);
		GlassRight = new ModelRenderer(this, 0, 191);
		GlassRight.addBox(0F, 0F, 0F, 1, 32, 30);
		GlassRight.setRotationPoint(19F, -9F, -6F);
		GlassRight.setTextureSize(512, 256);
		GlassRight.mirror = true;
		setRotation(GlassRight, 0F, 0F, 0F);
		GlassTopRight = new ModelRenderer(this, 0, 217);
		GlassTopRight.addBox(0F, 0F, 0F, 6, 1, 30);
		GlassTopRight.setRotationPoint(14F, -9F, -6F);
		GlassTopRight.setTextureSize(512, 256);
		GlassTopRight.mirror = true;
		setRotation(GlassTopRight, 0F, 0F, 0F);
		GlassTopLeft = new ModelRenderer(this, 0, 215);
		GlassTopLeft.addBox(0F, 0F, 0F, 6, 1, 30);
		GlassTopLeft.setRotationPoint(-9F, -9F, -6F);
		GlassTopLeft.setTextureSize(512, 256);
		GlassTopLeft.mirror = true;
		setRotation(GlassTopLeft, 0F, 0F, 0F);
		GlassTopBack = new ModelRenderer(this, 0, 220);
		GlassTopBack.addBox(0F, 0F, 0F, 19, 1, 5);
		GlassTopBack.setRotationPoint(-4F, -9F, -6F);
		GlassTopBack.setTextureSize(512, 256);
		GlassTopBack.mirror = true;
		setRotation(GlassTopBack, 0F, 0F, 0F);
		GlassTopFront = new ModelRenderer(this, 0, 220);
		GlassTopFront.addBox(0F, 0F, 0F, 19, 1, 5);
		GlassTopFront.setRotationPoint(-4F, -9F, 18F);
		GlassTopFront.setTextureSize(512, 256);
		GlassTopFront.mirror = true;
		setRotation(GlassTopFront, 0F, 0F, 0F);
		TopLid = new ModelRenderer(this, 108, 25);
		TopLid.addBox(0F, 0F, 0F, 15, 1, 16);
		TopLid.setRotationPoint(-2F, -11F, 1F);
		TopLid.setTextureSize(512, 256);
		TopLid.mirror = true;
		setRotation(TopLid, 0F, 0F, 0F);
		BottomLid = new ModelRenderer(this, 108, 0);
		BottomLid.addBox(0F, 0F, 0F, 17, 1, 19);
		BottomLid.setRotationPoint(-3F, -10F, -1F);
		BottomLid.setTextureSize(512, 256);
		BottomLid.mirror = true;
		setRotation(BottomLid, 0F, 0F, 0F);
		BottomBaseRight = new ModelRenderer(this, 0, 136);
		BottomBaseRight.addBox(0F, 0F, 0F, 11, 3, 32);
		BottomBaseRight.setRotationPoint(20F, 20.7F, -9.2F);
		BottomBaseRight.setTextureSize(512, 256);
		BottomBaseRight.mirror = true;
		setRotation(BottomBaseRight, 0F, 0F, 0F);
		BottomTopRight = new ModelRenderer(this, 0, 110);
		BottomTopRight.addBox(0F, 0F, 0F, 11, 12, 46);
		BottomTopRight.setRotationPoint(20F, 9F, -9F);
		BottomTopRight.setTextureSize(512, 256);
		BottomTopRight.mirror = true;
		setRotation(BottomTopRight, 0F, 0F, 0F);
		BottomBack = new ModelRenderer(this, 0, 125);
		BottomBack.addBox(0F, 0F, -1F, 52, 12, 10);
		BottomBack.setRotationPoint(-21F, 7.9F, -16F);
		BottomBack.setTextureSize(512, 256);
		BottomBack.mirror = true;
		setRotation(BottomBack, -0.1396263F, 0F, 0F);
		BottomBaseLeftFront = new ModelRenderer(this, 0, 66);
		BottomBaseLeftFront.addBox(0F, 0F, 0F, 11, 3, 15);
		BottomBaseLeftFront.setRotationPoint(-21F, 20.7F, 22.2F);
		BottomBaseLeftFront.setTextureSize(512, 256);
		BottomBaseLeftFront.mirror = true;
		setRotation(BottomBaseLeftFront, 0.1650834F, 0F, 0F);
		BottomTopLeft = new ModelRenderer(this, 0, 111);
		BottomTopLeft.addBox(0F, 0F, 0F, 11, 12, 46);
		BottomTopLeft.setRotationPoint(-21F, 9F, -9F);
		BottomTopLeft.setTextureSize(512, 256);
		BottomTopLeft.mirror = true;
		setRotation(BottomTopLeft, 0F, 0F, 0F);
		BottomBaseLeft = new ModelRenderer(this, 0, 136);
		BottomBaseLeft.addBox(0F, 0F, 0F, 11, 3, 32);
		BottomBaseLeft.setRotationPoint(-21F, 20.7F, -9.2F);
		BottomBaseLeft.setTextureSize(512, 256);
		BottomBaseLeft.mirror = true;
		setRotation(BottomBaseLeft, 0F, 0F, 0F);
		BottomBaseBackLeft = new ModelRenderer(this, 0, 124);
		BottomBaseBackLeft.addBox(0F, 0F, 0F, 52, 3, 10);
		BottomBaseBackLeft.setRotationPoint(-21F, 16.9F, -17.4F);
		BottomBaseBackLeft.setTextureSize(512, 256);
		BottomBaseBackLeft.mirror = true;
		setRotation(BottomBaseBackLeft, -0.3885165F, 0F, 0F);
		AdvancedMachinePart = new ModelRenderer(this, 17, 68);
		AdvancedMachinePart.addBox(0F, 0F, 0F, 1, 1, 11);
		AdvancedMachinePart.setRotationPoint(8F, -15F, 0F);
		AdvancedMachinePart.setTextureSize(512, 256);
		AdvancedMachinePart.mirror = true;
		setRotation(AdvancedMachinePart, 0F, 0F, 0F);
		TopLidIronBottom = new ModelRenderer(this, 21, 26);
		TopLidIronBottom.addBox(0F, 0F, 0F, 3, 3, 3);
		TopLidIronBottom.setRotationPoint(4F, -14F, 7F);
		TopLidIronBottom.setTextureSize(512, 256);
		TopLidIronBottom.mirror = true;
		setRotation(TopLidIronBottom, 0F, 0F, 0F);
		AdvancedMachinePart1 = new ModelRenderer(this, 118, 120);
		AdvancedMachinePart1.addBox(0F, 0F, 0F, 21, 1, 1);
		AdvancedMachinePart1.setRotationPoint(-5F, -11.3F, -1.7F);
		AdvancedMachinePart1.setTextureSize(512, 256);
		AdvancedMachinePart1.mirror = true;
		setRotation(AdvancedMachinePart1, -2.268928F, 0F, -0.002618F);
		AdvancedMachinePart2 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart2.addBox(0F, 0F, 0F, 1, 1, 3);
		AdvancedMachinePart2.setRotationPoint(12F, -12F, -6.5F);
		AdvancedMachinePart2.setTextureSize(512, 256);
		AdvancedMachinePart2.mirror = true;
		setRotation(AdvancedMachinePart2, 0F, 1.570796F, 0F);
		TopLidIronTop = new ModelRenderer(this, 17, 26);
		TopLidIronTop.addBox(0F, 0F, 0F, 5, 1, 5);
		TopLidIronTop.setRotationPoint(3F, -15F, 6F);
		TopLidIronTop.setTextureSize(512, 256);
		TopLidIronTop.mirror = true;
		setRotation(TopLidIronTop, 0F, 0F, 0F);
		TopMachinePartRight = new ModelRenderer(this, 0, 120);
		TopMachinePartRight.addBox(0F, 0F, 0F, 11, 8, 12);
		TopMachinePartRight.setRotationPoint(20F, -1F, -11F);
		TopMachinePartRight.setTextureSize(512, 256);
		TopMachinePartRight.mirror = true;
		setRotation(TopMachinePartRight, 0F, 0F, 0F);
		GlassLeft = new ModelRenderer(this, 0, 191);
		GlassLeft.addBox(0F, 0F, 0F, 1, 32, 30);
		GlassLeft.setRotationPoint(-10F, -9F, -6F);
		GlassLeft.setTextureSize(512, 256);
		GlassLeft.mirror = true;
		setRotation(GlassLeft, 0F, 0F, 0F);
		MahcinePartConnection = new ModelRenderer(this, 0, 120);
		MahcinePartConnection.addBox(0F, 0F, 0F, 52, 8, 8);
		MahcinePartConnection.setRotationPoint(-21F, 2F, -15F);
		MahcinePartConnection.setTextureSize(512, 256);
		MahcinePartConnection.mirror = true;
		setRotation(MahcinePartConnection, 0F, 0F, 0F);
		TopMachinePartLeft = new ModelRenderer(this, 0, 120);
		TopMachinePartLeft.addBox(0F, 0F, 0F, 11, 8, 12);
		TopMachinePartLeft.setRotationPoint(-21F, -1F, -11F);
		TopMachinePartLeft.setTextureSize(512, 256);
		TopMachinePartLeft.mirror = true;
		setRotation(TopMachinePartLeft, 0F, 0F, 0F);
		AdvancedMachinePartBack = new ModelRenderer(this, 0, 120);
		AdvancedMachinePartBack.addBox(0F, 0F, 0F, 52, 8, 14);
		AdvancedMachinePartBack.setRotationPoint(-21F, -1F, -21F);
		AdvancedMachinePartBack.setTextureSize(512, 256);
		AdvancedMachinePartBack.mirror = true;
		setRotation(AdvancedMachinePartBack, 0F, 0F, 0F);
		AdvancedMahinePart3 = new ModelRenderer(this, 0, 67);
		AdvancedMahinePart3.addBox(0F, 0F, 0F, 19, 1, 8);
		AdvancedMahinePart3.setRotationPoint(-4F, -2F, -15F);
		AdvancedMahinePart3.setTextureSize(512, 256);
		AdvancedMahinePart3.mirror = true;
		setRotation(AdvancedMahinePart3, 0F, 0F, 0F);
		AdvancedMachinePart4 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart4.addBox(0F, 0F, 0F, 1, 1, 11);
		AdvancedMachinePart4.setRotationPoint(2F, -15F, 0F);
		AdvancedMachinePart4.setTextureSize(512, 256);
		AdvancedMachinePart4.mirror = true;
		setRotation(AdvancedMachinePart4, 0F, 0F, 0F);
		AdvancedMachinePart5 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart5.addBox(0F, 0F, 0F, 1, 1, 9);
		AdvancedMachinePart5.setRotationPoint(12F, -11.1F, -3F);
		AdvancedMachinePart5.setTextureSize(512, 256);
		AdvancedMachinePart5.mirror = true;
		setRotation(AdvancedMachinePart5, 2.426008F, 0F, 0F);
		AdvancedMachinePart6 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart6.addBox(0F, 0F, 0F, 1, 1, 11);
		AdvancedMachinePart6.setRotationPoint(-3F, -2F, -14F);
		AdvancedMachinePart6.setTextureSize(512, 256);
		AdvancedMachinePart6.mirror = true;
		setRotation(AdvancedMachinePart6, 1.308997F, 0F, 0F);
		AdvancedMachinePart7 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart7.addBox(0F, 0F, 0F, 1, 1, 11);
		AdvancedMachinePart7.setRotationPoint(-3F, -2F, -11F);
		AdvancedMachinePart7.setTextureSize(512, 256);
		AdvancedMachinePart7.mirror = true;
		setRotation(AdvancedMachinePart7, 1.308997F, 0F, 0F);
		BottomBaseRightFront = new ModelRenderer(this, 0, 66);
		BottomBaseRightFront.addBox(0F, 0F, 0F, 11, 3, 15);
		BottomBaseRightFront.setRotationPoint(20F, 20.7F, 22.2F);
		BottomBaseRightFront.setTextureSize(512, 256);
		BottomBaseRightFront.mirror = true;
		setRotation(BottomBaseRightFront, 0.1650834F, 0F, 0F);
		AdvancedMachinePart8 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart8.addBox(0F, 0F, 0F, 1, 1, 5);
		AdvancedMachinePart8.setRotationPoint(12F, -12F, -11.5F);
		AdvancedMachinePart8.setTextureSize(512, 256);
		AdvancedMachinePart8.mirror = true;
		setRotation(AdvancedMachinePart8, 0F, 0F, 0F);
		AdvancedMachinePart9 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart9.addBox(0F, 0F, 0F, 1, 1, 5);
		AdvancedMachinePart9.setRotationPoint(-2F, -12F, -11.5F);
		AdvancedMachinePart9.setTextureSize(512, 256);
		AdvancedMachinePart9.mirror = true;
		setRotation(AdvancedMachinePart9, 0F, 0F, 0F);
		AdvancedMachinePart10 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart10.addBox(0F, 0F, 0F, 1, 1, 3);
		AdvancedMachinePart10.setRotationPoint(-4F, -12F, -6.5F);
		AdvancedMachinePart10.setTextureSize(512, 256);
		AdvancedMachinePart10.mirror = true;
		setRotation(AdvancedMachinePart10, 0F, 1.570796F, 0F);
		AdvancedMachinePart11 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart11.addBox(0F, 0F, 0F, 1, 1, 11);
		AdvancedMachinePart11.setRotationPoint(13F, -2F, -14F);
		AdvancedMachinePart11.setTextureSize(512, 256);
		AdvancedMachinePart11.mirror = true;
		setRotation(AdvancedMachinePart11, 1.308997F, 0F, 0F);
		AdvancedMachinePart12 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart12.addBox(0F, 0F, 0F, 1, 2, 6);
		AdvancedMachinePart12.setRotationPoint(-2F, -12F, -10F);
		AdvancedMachinePart12.setTextureSize(512, 256);
		AdvancedMachinePart12.mirror = true;
		setRotation(AdvancedMachinePart12, 1.570796F, 0F, 0F);
		AdvancedMachinePart13 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart13.addBox(0F, 0F, 0F, 1, 1, 11);
		AdvancedMachinePart13.setRotationPoint(13F, -2F, -11F);
		AdvancedMachinePart13.setTextureSize(512, 256);
		AdvancedMachinePart13.mirror = true;
		setRotation(AdvancedMachinePart13, 1.308997F, 0F, 0F);
		AdvancedMachinePart14 = new ModelRenderer(this, 118, 52);
		AdvancedMachinePart14.addBox(0F, 0F, 0F, 7, 1, 5);
		AdvancedMachinePart14.setRotationPoint(2F, -14.4F, 0.8F);
		AdvancedMachinePart14.setTextureSize(512, 256);
		AdvancedMachinePart14.mirror = true;
		setRotation(AdvancedMachinePart14, -2.268928F, 0F, 0F);
		AdvancedMachinePart15 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart15.addBox(0F, 0F, 0F, 1, 1, 3);
		AdvancedMachinePart15.setRotationPoint(12F, -12F, -11.5F);
		AdvancedMachinePart15.setTextureSize(512, 256);
		AdvancedMachinePart15.mirror = true;
		setRotation(AdvancedMachinePart15, 0F, 1.570796F, 0F);
		AdvancedMachinePart16 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart16.addBox(0F, 0F, 0F, 1, 1, 5);
		AdvancedMachinePart16.setRotationPoint(14F, -12F, -11.5F);
		AdvancedMachinePart16.setTextureSize(512, 256);
		AdvancedMachinePart16.mirror = true;
		setRotation(AdvancedMachinePart16, 0F, 0F, 0F);
		AdvancedMachinePart17 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart17.addBox(0F, 0F, 0F, 1, 1, 5);
		AdvancedMachinePart17.setRotationPoint(-4F, -12F, -11.5F);
		AdvancedMachinePart17.setTextureSize(512, 256);
		AdvancedMachinePart17.mirror = true;
		setRotation(AdvancedMachinePart17, 0F, 0F, 0F);
		AdvancedMachinePart18 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart18.addBox(0F, 0F, 0F, 1, 1, 3);
		AdvancedMachinePart18.setRotationPoint(-4F, -12F, -11.5F);
		AdvancedMachinePart18.setTextureSize(512, 256);
		AdvancedMachinePart18.mirror = true;
		setRotation(AdvancedMachinePart18, 0F, 1.570796F, 0F);
		AdvancedMachinePart19 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart19.addBox(0F, 0F, 0F, 1, 2, 6);
		AdvancedMachinePart19.setRotationPoint(12F, -12F, -10F);
		AdvancedMachinePart19.setTextureSize(512, 256);
		AdvancedMachinePart19.mirror = true;
		setRotation(AdvancedMachinePart19, 1.570796F, 0F, 0F);
		AdvancedMachinePart20 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart20.addBox(0F, 0F, 0F, 1, 2, 6);
		AdvancedMachinePart20.setRotationPoint(-4F, -12F, -10F);
		AdvancedMachinePart20.setTextureSize(512, 256);
		AdvancedMachinePart20.mirror = true;
		setRotation(AdvancedMachinePart20, 1.570796F, 0F, 0F);
		AdvancedMachinePart21 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart21.addBox(0F, 0F, 0F, 1, 2, 6);
		AdvancedMachinePart21.setRotationPoint(14F, -12F, -10F);
		AdvancedMachinePart21.setTextureSize(512, 256);
		AdvancedMachinePart21.mirror = true;
		setRotation(AdvancedMachinePart21, 1.570796F, 0F, 0F);
		AdvancedMachinePart22 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart22.addBox(0F, 0F, 0F, 1, 1, 9);
		AdvancedMachinePart22.setRotationPoint(-2F, -11.1F, -3F);
		AdvancedMachinePart22.setTextureSize(512, 256);
		AdvancedMachinePart22.mirror = true;
		setRotation(AdvancedMachinePart22, 2.426008F, 0F, 0F);
		AdvancedMachinePart23 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart23.addBox(0F, 0F, 0F, 1, 1, 9);
		AdvancedMachinePart23.setRotationPoint(14F, -11.1F, -3F);
		AdvancedMachinePart23.setTextureSize(512, 256);
		AdvancedMachinePart23.mirror = true;
		setRotation(AdvancedMachinePart23, 2.426008F, 0F, 0F);
		AdvancedMachinePart24 = new ModelRenderer(this, 17, 66);
		AdvancedMachinePart24.addBox(0F, 0F, 0F, 1, 1, 9);
		AdvancedMachinePart24.setRotationPoint(-4F, -11.1F, -3F);
		AdvancedMachinePart24.setTextureSize(512, 256);
		AdvancedMachinePart24.mirror = true;
		setRotation(AdvancedMachinePart24, 2.426008F, 0F, 0F);
	}
	
	public void render(float scale)
	{
		Bottom.render(scale);
		ChairBase.render(scale);
		ChairHeadRod1.render(scale);
		ChairHandRight.render(scale);
		ChairSeat.render(scale);
		ChairHandLeft.render(scale);
		ChairSeatBack.render(scale);
		ChairHead.render(scale);
		ChairHeadRod.render(scale);
		ChairBaseRod.render(scale);
		
		glEnable(GL_BLEND);
		glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
		GlassBack.render(scale);
		GlassRight.render(scale);
		GlassTopRight.render(scale);
		GlassTopLeft.render(scale);
		GlassTopBack.render(scale);
		GlassTopFront.render(scale);
		GlassLeft.render(scale);
		FrontGlass.render(scale);
		glDisable(GL_BLEND);
		
		TopLid.render(scale);
		BottomLid.render(scale);
		BottomBaseRight.render(scale);
		BottomTopRight.render(scale);
		BottomBack.render(scale);
		BottomBaseLeftFront.render(scale);
		BottomTopLeft.render(scale);
		BottomBaseLeft.render(scale);
		BottomBaseBackLeft.render(scale);
		AdvancedMachinePart.render(scale);
		TopLidIronBottom.render(scale);
		AdvancedMachinePart1.render(scale);
		AdvancedMachinePart2.render(scale);
		TopLidIronTop.render(scale);
		TopMachinePartRight.render(scale);
		MahcinePartConnection.render(scale);
		TopMachinePartLeft.render(scale);
		AdvancedMachinePartBack.render(scale);
		AdvancedMahinePart3.render(scale);
		AdvancedMachinePart4.render(scale);
		AdvancedMachinePart5.render(scale);
		AdvancedMachinePart6.render(scale);
		AdvancedMachinePart7.render(scale);
		BottomBaseRightFront.render(scale);
		AdvancedMachinePart8.render(scale);
		AdvancedMachinePart9.render(scale);
		AdvancedMachinePart10.render(scale);
		AdvancedMachinePart11.render(scale);
		AdvancedMachinePart12.render(scale);
		AdvancedMachinePart13.render(scale);
		AdvancedMachinePart14.render(scale);
		AdvancedMachinePart15.render(scale);
		AdvancedMachinePart16.render(scale);
		AdvancedMachinePart17.render(scale);
		AdvancedMachinePart18.render(scale);
		AdvancedMachinePart19.render(scale);
		AdvancedMachinePart20.render(scale);
		AdvancedMachinePart21.render(scale);
		AdvancedMachinePart22.render(scale);
		AdvancedMachinePart23.render(scale);
		AdvancedMachinePart24.render(scale);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
}